### ISSUE TITLE
Unit testing for postview and post detail

### ISSUE THREAD

**Issue by Pramilashanmugam** [Pramilashanmugam/GrooveMates_backend#10]
As a developer, I want to **create unit testing** so  that I can **ensure the developed codes outcome meets the requirement**.

**Acceptance Criteria:**

- [x]  all test cases should pass.

- [x]  test cases for authorised and unauthorised users should be created.

- [x]  test cases for post view and post detail should be available.
